import Head from "next/head";
import Image from "next/image";
import NumberInput from "../components/input/number-input";
import TextInput from "../components/input/text-input";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-40">
        <div className="grid grid-cols-1 pt-10 pb-6 lg:grid-cols-2 lg:gap-20 ">
          <div className="space-y-4 ">
            <div className="relative h-[35rem] aspect-square">
              <Image
                layout="fill"
                src={`/assets/images/product-large.jpg`}
                alt={`product-large`}
                quality={100}
              />
              <div className="absolute bottom-0 right-0 flex items-end h-full p-4 space-x-1">
                <div className="flex items-center justify-center w-8 h-8 border border-white">
                  <div className="relative w-3 h-2 ">
                    <Image
                      src="/assets/icons/svg/left.svg"
                      alt="left icon"
                      layout="fill"
                    />
                  </div>
                </div>
                <div className="flex items-center justify-center w-8 h-8 border border-white">
                  <div className="relative w-3 h-2 ">
                    <Image
                      src="/assets/icons/svg/right.svg"
                      alt="right icon"
                      layout="fill"
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className="grid grid-cols-6 gap-4 w-[35rem]">
              <div>
                <div className="relative w-full h-full aspect-square">
                  <Image
                    layout="fill"
                    src={`/assets/images/product-small.jpg`}
                    alt={`product-small`}
                  />
                </div>
              </div>
              <div>
                <div className="relative w-full h-full aspect-square">
                  <Image
                    layout="fill"
                    src={`/assets/images/product-small.jpg`}
                    alt={`product-small`}
                  />
                </div>
              </div>
              <div>
                <div className="relative w-full h-full aspect-square">
                  <Image
                    layout="fill"
                    src={`/assets/images/product-small.jpg`}
                    alt={`product-small`}
                  />
                </div>
              </div>
              <div>
                <div className="relative w-full h-full aspect-square">
                  <Image
                    layout="fill"
                    src={`/assets/images/product-small.jpg`}
                    alt={`product-small`}
                  />
                </div>
              </div>
              <div>
                <div className="relative w-full h-full aspect-square">
                  <Image
                    layout="fill"
                    src={`/assets/images/product-small.jpg`}
                    alt={`product-small`}
                  />
                </div>
              </div>
              <div>
                <div className="relative w-full h-full aspect-square">
                  <Image
                    layout="fill"
                    src={`/assets/images/product-small.jpg`}
                    alt={`product-small`}
                  />
                </div>
              </div>
            </div>
          </div>
          <div>
            <p className="flex items-center h-10 mb-4 text-2xl font-bold">
              Manchester United 21-22 Home Shirt
            </p>
            <div className="flex justify-between mb-10">
              <div className="flex items-center justify-center space-x-4">
                <p className="text-5xl font-bold leading-[48px] ">€30.00</p>
                <s className="text-lg font-normal text-red-500">€89.95</s>
                <div className="flex px-2 py-1 text-lg font-semibold text-white bg-green-500">
                  Save 67%
                </div>
              </div>
              <div className="flex items-center justify-center px-4 py-3 space-x-2 border">
                <div className="relative w-3 h-3">
                  <Image
                    layout="fill"
                    src={`/assets/icons/svg/heart-outline.svg`}
                    alt={`heart`}
                    className
                  />
                </div>
                <p>Add to Favorites</p>
              </div>
            </div>
            <div className="mb-10">
              <p className="text-sm leading-6">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Pellentesque euismod lacinia aliquam. Morbi est nis, at lacus.
                Donec ornare, dui vel facilisis luctus, metus mi ttitor erat
                sapien scelerisque nunc. Pellentesque ornare elit tellus...
                <span className="font-bold underline"> Read More</span>
              </p>
            </div>

            <div className="mb-10 space-y-6">
              <TextInput
                label="Size"
                name="size"
                placeholder="Select a shirt size"
                required={true}
              />
              <TextInput
                label="Name"
                name="name"
                placeholder="What name would you want in the shirt?"
              />
              <TextInput
                label="Number on Shirt"
                name="shirt_number"
                placeholder="Enter a number between 0 and 99"
              />
              <TextInput
                label="Patch"
                name="patch"
                placeholder="Select a patch"
              />
              <NumberInput
                label="Size"
                name="size"
                placeholder="Select a shirt size"
              />
            </div>
            <button className="flex w-full h-14">
              <div className="flex items-center justify-start w-full h-full px-6 py-4 font-semibold bg-yellow-300">
                Add to Cart
              </div>
              <div className="relative flex items-center justify-center h-full bg-black w-14">
                <Image
                  className="invert"
                  src="/assets/icons/svg/shopping-cart.svg"
                  alt="shopping cart"
                  height={20}
                  width={20}
                />
              </div>
            </button>
          </div>
        </div>
      </div>
      <div className="relative w-40 mb-20 h-14">
        <Image
          src="/assets/icons/svg/rewards-badge.svg"
          alt="rewards badge"
          layout="fill"
        />
      </div>
    </div>
  );
}
